# BASIC CALCULATOR (BEGINNER VERSION)

NUM1 = FLOAT(INPUT("ENTER FIRST NUMBER: "))
NUM2 = FLOAT(INPUT("ENTER SECOND NUMBER: "))
OP = INPUT("ENTER OPERATION (+, -, *, /): ")

IF OP == "+":
    PRINT(NUM1 + NUM2)
ELIF OP == "-":
    PRINT(NUM1 - NUM2)
ELIF OP == "*":
    PRINT(NUM1 * NUM2)
ELIF OP == "/":
    PRINT(NUM1 / NUM2)
ELSE:
    PRINT("INVALID OPERATION")
